### PR TITLE
configure, split superset for production/staging

### PR DESCRIPTION
**Pull request by v9n**
We map superset directly to docker bind port so there was no HTTPS before. Also domain was hard code in the config file.

This PR turn the hard code URL into dynamic env so we can pass from docker compose. We now can use the same compose file or config to serve both production and staging, customize based on passed env var.

### Staging
graphql: https://turing-staging.explorer.oak.tech/
superset: https://turing-staging.explorer.oak.tech:8088 

### Production

graphql: https://turing.explorer.oak.tech/
superset: https://turing.explorer.oak.tech:8088

### CODE REVIEW

**Review by chrisli30 — APPROVED** [review]
LGTM.

I tried to add my oak.tech email as a user, and have got two non-blockching questions.
1. How are the permissions of user defined? I see permissions Public, Alpha and Gammar. Are they pre-defined or arbitrary names?
2. Form confirmation will always result in an error page(wrong URL)? Clicking on the submission button after adding or updating a user will reproduce the problem.

**Comment by chrisli30** [comment]
@v9n , also let’s change the superset URL to the format of `turing-staging.insights.oak.tech`. Let me know what A record mapping to add on Namecheap.

**Comment by v9n** [comment]
I'm fixing other 2 issues now.

@chrisli30 Could you update 2 A records as below:

turing-staging.insights.oak.tech -> 	64.225.91.35
turing.explorer.oak.tech -> 143.244.208.113

**Comment by v9n** [comment]
@chrisli30 
> How are the permissions of user defined? I see permissions Public, Alpha and Gammar. Are they pre-defined or arbitrary names?

The role are a set of permissions. These are just one SuperSet pre-generate for us. We can re-define the set of permission a role has by going to Settings > List Role then it will allow us to edit and control granuality per role. Public role for example has no permission at all by default so can only watch public info.

> Form confirmation will always result in an error page(wrong URL)? Clicking on the submission button after adding or updating a user will reproduce the problem.

This is fixed now. The issue is because we run behind load balancer (with https) but from superset perspective it doesn't process TLS so it submit form back to http://. I corrected now so superset read those header https://github.com/OAK-Foundation/oak-subql/pull/19/commits/77f929dd77941651cb8491715c208e1b7eb2c385

> For domain

 Could you update 2 A records as below:


turing-staging.insights.oak.tech -> 64.225.91.35
turing.insights.oak.tech -> 143.244.208.113

**Review by chrisli30 — APPROVED** [review]

**Pull request merged**
